Remove images from the website
Igalia/wpewebkit.org pull request #152
Opened 2023-02-24 16:49 UTC by manuelafm

2023-02-24 18:06 UTC, mariospr requested changes
This is a good cleanup, but I think we need to include in this PR changes in any other places where they reference the Balena blocks, the yocto images and flatpak.

From what I can see, and besides what's included in his PR already, those other places are these:

  * https://wpewebkit.org/developers -> We should remove the 3 links pointing to flatpak, yocto and Balena in the WPE Builds section; and probably we'd like to reword the paragraph there to include the link to the "Linux distros" link in a more natural way now that we only have one item left.

  * https://wpewebkit.org/blog/04-wpe-qa-tooling.html -> I know it's a blog post, but still I think we should reword the "Testing WPE in the wild" section to only include the links to the "prebuild distro packages"; and again I would reword the section a bit now that we only have one item (and remove the last sentence i.d. "Some of these options...").

  * https://wpewebkit.org/blog/02-overview-of-wpe.html -> The last paragraph reference to the flatpak and balena pages too, so we need to do some rewording there to remove those as well.

  * https://wpewebkit.org/about/supported-hardware.html -> There is a link to "Try WPE with Flatpak" from the "Resources" section at the bottom. We need to remove that and replace it with something else; I'd suggest maybe linking to the [Blog](https://wpewebkit.org/blog/) section of the website, with an excerpt of the text at the top as preview text.

And I think that's it, or at least I could not find more pointers to those dead sections.

2023-02-24 18:37 UTC, manuelafm commented
> This is a good cleanup, but I think we need to include in this PR changes in any other places where they reference the Balena blocks, the yocto images and flatpak.
> 
> From what I can see, and besides what's included in his PR already, those other places are these:
> 
>     * https://wpewebkit.org/developers -> We should remove the 3 links pointing to flatpak, yocto and Balena in the WPE Builds section; and probably we'd like to reword the paragraph there to include the link to the "Linux distros" link in a more natural way now that we only have one item left.

Done.

>     * https://wpewebkit.org/blog/04-wpe-qa-tooling.html -> I know it's a blog post, but still I think we should reword the "Testing WPE in the wild" section to only include the links to the "prebuild distro packages"; and again I would reword the section a bit now that we only have one item (and remove the last sentence i.d. "Some of these options...").
> 
>     * https://wpewebkit.org/blog/02-overview-of-wpe.html -> The last paragraph reference to the flatpak and balena pages too, so we need to do some rewording there to remove those as well.

I am not sure that it is a good idea to change blog posts in general, but given that these are more like articles about WPE that we control instead of typical blog posts, I suppose that it's all right.

I tried to keep it as simple as possible by using a "greedy removing algorithm" and not trying to rephrase.

>     * https://wpewebkit.org/about/supported-hardware.html -> There is a link to "Try WPE with Flatpak" from the "Resources" section at the bottom. We need to remove that and replace it with something else; I'd suggest maybe linking to the [Blog](https://wpewebkit.org/blog/) section of the website, with an excerpt of the text at the top as preview text.

I think that removing it is fine?  The previous resource is the same "Get Started" already contains the rest, including containing Flatpak.
 
> And I think that's it, or at least I could not find more pointers to those dead sections.

I just pushed another change, but since I'm not going to be around the next week in general, please feel free to go ahead and make further changes.

2023-02-24 21:10 UTC, aperezdc requested changes
Patch LGTM overall, I have only a small nit, please check the comment.

2023-02-24 21:10 UTC, aperezdc commented on developers/index.md
> +There are also pre-build packages available for many <a href="{{ '/about/explore-wpe.html' | url }}">Linux distros</a>.
Let's use formal wording in a formal website: `s/distro/distribution/`&mdash;also for consistency with the other occurrences 😉 

```suggestion
There are also pre-build packages available for many <a href="{{ '/about/explore-wpe.html' | url }}">Linux distributions</a>.
```

2023-02-28 11:38 UTC, mariospr reviewed
I agree with the changes proposed by @aperezdc and also with the latest changes done by @manuelafm following my previous comments, but at this point I'd like to get the feedback from either @bkardell or @meyerweb since there are some changes in the wording when removing those lists, that might need some massaging :innocent:

2023-03-06 12:41 UTC, manuelafm commented
@bkardell or @meyerweb , feedback please?

2023-03-06 18:46 UTC, meyerweb commented
> @bkardell or @meyerweb , feedback please?

Looks good to me, at least from an editing point of view.  (No idea if the changes are technically accurate or not, so can’t comment on that part.)

2023-03-07 06:30 UTC, mariospr approved these changes
LGTM now, thanks

2023-03-07 06:31 UTC, merged